from build_deliverables import *
import fitz

G=[]
def gap(priority,document,route,status,questions,action):G.append({'id':f'G{len(G)+1:02}','priority':priority,'missing_or_replacement_material':document,'verified_official_route':route,'access_status':status,'questions_blocked':questions,'next_action':action})
gap('P1','Milan service-specific current operating timetable, partial-settlement windows and subsequent amendments',cite('92d6cd189bff','current rules hub')+'; '+cite('2ab6ff0cf5b5','operational notices hub')+'; '+cite('8719262f5e8b','Articles 66–67'),'Public hubs accessed; resolving notice not located','Exact participant submission/settlement cut-offs and local current timetable','Locate the notice that supersedes June 2025 clock clauses or obtain service confirmation; preserve F01 conflict meanwhile.')
gap('P1','Dated ECB T2S operational notices and their later updates',cite('t2s-2026-status-events','2026 status-event feed'),'Public; newly saved and selected events reviewed','Actual versus nominal cut-offs and daily incident effects','Ingest event-level records with business date, currency, timestamp and replacement/update relation; use September 8 as regression fixture.')
gap('P1','Standard for Users X-TRM A2A and RNI mode: current production edition and separate under-review November changes',cite('de2d312169fc','ON_36/2026 PDF 1; MT-X → Documentation → Live Services → Technical Documentation → Under review → Market Request'),'Client-platform dependency stated in official notice; no authenticated MT-X access attempted','Exact market identifiers, source values, bank-to-Milan messages and current/future mapping','Retrieve the named standard through authorised client access. Keep current production and planned November 30 version separate, with test-success condition. Current production folder/version not verified.')
gap('P1','ISIN-specific settlement eligibility, security CSD links / MT23 and applicable gateway route',cite('1bd67deaace2','T2S Gateway — Milan settlement links, valid from 1 May 2026')+'; '+cite('8719262f5e8b','Article 65'),'Public route guide already archived; operational/static-data access depends on client service','Can ISIN X settle through CSDs A/B in currency Y and which accounts/counterparty fields apply?','Review relevant route section in existing gateway manual first; obtain current MT-X eligibility/static-data extract and effective date. Do not substitute European Offering workbook.')
gap('P1','UDFS Diagram 55 structured matching-field matrix and dependent conditions',cite('aa3d5a3b94c9','R2026.JUN PDF 269, Diagram 55, footnote 194'),'Public original available; text extraction materially incomplete','Complete mandatory matching-field questions and conditions by payment type','Create validated matrix from original image, preserve diagram/footnote/page; compare to message usage/XSD before production-schema use.')
gap('P1','English DORA evidence plus current incident-reporting implementation instruments',cite('dora-english-oj','English OJ replacement, Articles 2 and 64')+'; '+cite('7b0958fc577e','ESMA CSDR regulatory hub'),'English base law saved; technical/national incident-reporting chain not audited','English legal citations; complete CSD incident reports, classification, timing and forms','Replace English-labelled French chunks. Build article-to-RTS/ITS/national-reporting dependencies before asserting operational obligations; exact current implementation versions remain to be established.')
gap('P2','Finanstilsynet approval of VPO NOK rulebook effective 2 September 2024, or unconditional successor',cite('1ee1619da83d','Norwegian supervisor infrastructure page')+'; '+cite('5f94dc198cb5','official Norwegian CSD legal hub'),'Public hubs accessed; edition-specific approval not located','Unconditional legal status, finality and binding current VPO NOK duties','Obtain exact edition approval; system approval alone is insufficient. No email/request was sent.')
gap('P2','HCMC decision 1/1074/4 December 2025 and Gazette B 6784/16 December 2025 cited by Athens master',cite('athens-greek-master','amendment table PDF 2; Section XIII Part 9 PDF 206')+'; '+cite('bc84b72f1f1e','Greek regulatory hub')+'; '+cite('57a7e76436ca','HCMC CSD authority route'),'Greek/English master saved; HCMC route connection refused; independent Gazette text not obtained','Independent approval history and precise provision-effective chain','Obtain cited decision/Gazette from official authority or gazette archive; keep documentary claims distinct from independent approval verification.')
gap('P2','Porto Notice 25/1162 Closing days in 2026 and Notice 0394/2024 Timetables',cite('porto-working-hours','2026 calendar and operating-hour table'),'Public page accessed and saved; underlying notices referenced but not read','Binding Porto service-calendar and all current cut-offs','Fetch named notices through official calendar/MyInterbolsa public notices. Check later amendments; webpage is useful supporting evidence, not complete contractual chain.')
gap('P2','Copenhagen DCP User Guidelines, service-specific Technical Characteristics and accepted tests',cite('a7e4ccfb2933','Part 5 §§2–3')+'; '+cite('bb6de3777121','current Copenhagen rulebook hub'),'Rulebook public; exact guide/version and portal entitlement not inspected','Production DCP connectivity, tests, message parameters and reports','Obtain guide named by Part 5 and map it to current service agreement and T2S release. Do not label all specifications private merely because some are unreviewed.')
gap('P2','Current Oslo user documentation/MyVPS interfaces and VPO NOK cycle/default/incident runbooks',cite('838261c7c0d4','Registration rules, account-operator and user-documentation dependencies')+'; '+cite('c34a73ae5e55','Oslo legal hub'),'Public rules read selectively; MyVPS authenticated documentation not inspected','Exact fields, reports, operational calendar and exception/default handling','Identify exact current manual titles/versions via CSD documentation service; these titles are not known from the reviewed public passages. Do not fabricate them.')
gap('P2','ATHEXCSD DSS technical announcements: settlement cycles, current file formats, statuses and certification',cite('410859953fce','Resolution 5 §2.2 PDF 4–5')+'; '+cite('f56e1ee3a8dd','Athens regulatory hub'),'Public rules available; exact production technical set/access route not tested','DSS production lifecycle, cut-offs and field-level answers','Retrieve the referenced current ATHEXCSD technical notices/specification set, then reconcile with Greek master and resolutions. Staff certification is a separate dependency.')
gap('P2','Porto public financial-intermediary file layouts and ISO15022 message specifications',cite('67c9ce673c2a','existing public file-layout original')+'; '+cite('04b490f176fe','existing ISO15022 original'),'Already archived and hashes refreshed; not substantively reviewed','Exact local file fields and status/report semantics','Prioritise substantive review of existing public specifications; validate versions, required fields, conditional blocks and example messages before requesting private access.')
gap('P2','T2S R2026.JUN MyStandards usage guidelines and exact message/schema dependencies',cite('c164d86ada8e','Annex B, PDF 2 onward')+'; '+cite('3e641cdb2b46','ECB SDD hub'),'ECB note public; linked MyStandards message packages not authenticated/validated','Exact production message field and usage-rule questions','Use per-message links preserved in evidence/mystandards-links.json; confirm requested message/release, imports and client entitlements. UDFS message overview alone is not the complete package.')
gap('P2','T2S R2026.NOV final publication and eventual deployment evidence',cite('3e641cdb2b46','ECB SDD hub')+'; '+cite('7244cf50f753','draft note publication plan'),'Live hub still exposed draft at audit; final publication not verified','Which November version is authoritative for testing versus production?','Locate final note and hashes; retain draft state until verified, and require separate deployment evidence before current operational promotion.')
gap('P2','CMVM Regulation 5/2018 as amended by 4/2025, and operational reporting/publication dependencies',cite('cd837a71029f','Official Gazette, 4/2025 Articles 1–2 and 7'),'Official text read via web; direct HTTP shell is incomplete','Portuguese CSD-operator information duties and publication of rules','Save full legal text/official PDF and consolidated amendment chain; current machine capture must not be indexed as if complete.')
gap('P2','Milan CLIMP static-data/application guide; MyEuronext corporate-event entitlements; dated local fee/tax/disclosure packs',cite('dd1cf7cb930b','§1.1 PDF 7–8 describes CLIMP')+'; '+cite('e1354fb2d76a','§2.3 PDF 17')+'; '+cite('70cf046f2af0','MyEuronext access form, not operating authority'),'Platforms/administrative references encountered; authenticated guides not inspected; several public fee documents already saved','Complete onboarding, cash-agent/account mapping and event/tax/fee workflows','Separate access forms from service procedures. Review existing public tariff and disclosure clauses first; obtain exact client guide only where required. No login credentials or external messages were requested.')
js('MISSING-SOURCES.json',G)
write('MISSING-SOURCES.md','# Missing, replacement and unreviewed dependencies\n\nVerified routes below were accessed in this audit or are direct official documents whose bytes were refreshed. A verified route does not mean the dependency behind it was downloaded or approved. No private portal login or external communication was attempted. Missing-version names remain unknown. Prioritise public material already archived before requesting client documentation.\n\n'+table(['ID','Priority','Material','Official route and locator','Access / evidence status','Questions blocked','Next action'],[[g['id'],g['priority'],g['missing_or_replacement_material'],g['verified_official_route'],g['access_status'],g['questions_blocked'],g['next_action']] for g in G]))

note=fitz.open(A/'sources/c164d86ada8e.pdf')
links=[{'pdf_page':n+1,'url':l['uri']} for n,p in enumerate(note) for l in p.get_links() if 'mystandards' in l.get('uri','').lower()]
js('evidence/mystandards-links.json',links)

CR=[
 ['HOW-CSD-WORKS: five local systems and legal relationships','Supported at the sampled level. Existing warning that branding/common-platform plans do not erase local rules is appropriate.',cite('3d76a327339b','§§2.2–2.3 PDF 3–4')+'; '+cite('410859953fce','§§1.1–1.2 PDF 3–4'),'Retain; local current eligibility and Oslo approval still qualified.'],
 ['HOW-CSD-WORKS: typical lifecycle and matching versus settlement','Supported, but needs claim-level local finality citations.',cite('aa3d5a3b94c9','PDF 267–271,303–304')+'; '+cite('8719262f5e8b','Articles 69–72 PDF 50–51'),'Add SF1/SF2/SF3 and Art 70(2) exception; matching is not posting but has legal consequences.'],
 ['HOW-CSD-WORKS: Oslo substitute bank is not a funding guarantee','Supported by sampled provision, conditional on unresolved edition status.',cite('14dc34b8e54e','§§9–10 PDF 17–18'),'Keep the approval caveat adjacent to this claim, not only in another register.'],
 ['HOW-CSD-WORKS / REQUIREMENTS-MAP: daily reconciliation and segregation','Role-level anchor supported; local implementation remains partial.',cite('02014R0909-20260117','Articles 37–38')+'; '+cite('089b7aaef991','§7.1 PDF 66'),'Use CSD obligation versus participant procedure labels. Do not infer all jurisdictional account models.'],
 ['HOW-CSD-WORKS: July 2026 Milan register extension','Source has a recent extension, but the text should identify its ancillary-service type.',cite('535f6a23062a','Authorised CSDs row 36'),'Specify UK stamp duty; avoid implying new general settlement permission.'],
 ['HOW-CSD-WORKS: future programmes and T+1','Separation is appropriate at 13 September; supporting state should be refreshed with legal/release evidence.',cite('271556895d29','announcement')+'; '+cite('625e85423963','programme hub')+'; '+cite('32025R2075','Articles 1–2')+'; '+cite('591deafae0a9','Article 2'),'Keep European Offering September 21 future and Convergence provisional; label T+1 enacted/future application; preserve staggered RTS dates and OJ uncertainty.'],
 ['Existing investor-CSD discussion and cross-csd-message-flow.png','Broad DvP ICP illustration supported by current UDFS for its stated assumptions; programme SDD is supplementary future design.',cite('aa3d5a3b94c9','PDF 373–376,385–387,753,778'),'Use current UDFS as primary. Add explicit cash-bank actor/account effects, link assumptions and legal finality. Do not treat it as a security-for-security swap.'],
 ['READING-GUIDE / CURRENTNESS-REGISTER default selections','Useful navigation, not verified production eligibility.', 'F01–F12; SOURCE-DECISIONS.json and REVIEWED-SOURCES.md','Replace document-wide defaults with conditional section proposals; narrow Athens label issue, retain Oslo reservation.'],
 ['REQUIREMENTS-MAP: regulatory/admission checklists','Appropriately labelled evidence checklist, not complete application dossier. Many listed legal articles/procedures were not substantively checked in this audit.','COVERAGE-MATRIX.md, role and status columns','Do not convert its checklists into attested requirements or independent evidence.'],
 ['COVERAGE-AND-CAVEATS / README acquisition versus review distinction','Honest and consistent with this audit: 800 files, 787 unique hashes, 29,084 PDF pages; no claim of full substantive review.','evidence/inventory-check.json','Preserve distinction; add body-language checks and archive-member extraction status.'],
 ['FULL-DOCUMENT-LIST discussion citations and attachment','Discussion provenance exists; the v1.5 attachment is programme design and is not an independent current authority.','metadata/discussion-sources.json; user attachment identity','Keep derivatives and source versions separate. This audit does not claim to have reread all previously cited Convergence passages.']
]
write('CLAIM-REVIEW.md','# Review of existing explanations\n\n'+table(['Affected explanation','Assessment','Evidence','Proposed correction'],CR)+f'''

## A bounded cross-CSD explanation for the knowledge base

This is an illustration, not an executable settlement instruction. Assume one eligible ISIN, a direct valid link between two CSDs both participating in T2S, seller at the issuer CSD, buyer at the investor CSD, both banks indirectly connected through their CSDs, EUR DvP for 100 shares and EUR 1,000, and separate eligible cash accounts with sufficient resources. No external CSD, multi-issuance, alternative chain, hold or partial settlement is assumed. These assumptions must be checked for a real transaction. The investor CSD holds through an omnibus account at its technical issuer; more complex chains are possible. {cite('aa3d5a3b94c9','§1.6.1.10 PDF 375–376,385–387')}.

1. The banks or their agents send instructions through their local CSD interfaces. For this ICP scenario the CSDs submit native T2S instructions. DCP changes the technical message path; it does not automatically replace CSD membership or the cash-bank arrangement. {cite('dd1cf7cb930b','§1.1 PDF 7–8')}; {cite('fcbc69b0fc35','Article 2(4) PDF 2')}.
2. T2S validates and matches compatible instructions. Matching can precede the intended settlement date and does not establish the availability or transfer of cash/securities. For Milan, completed validation is SF1; matching is SF2 subject to the bilateral-cancellation qualification. {cite('aa3d5a3b94c9','PDF 267–271,303–304')}; {cite('8719262f5e8b','Articles 69–72 PDF 50–51')}.
3. T2S determines the realignment chain from configured CSD/security/account links and generates the necessary instructions. These use the relevant omnibus, mirror and (where applicable) inter-CSD accounts; generation is not a completed ledger transfer. Business and generated realignment instructions settle all-or-none. {cite('aa3d5a3b94c9','PDF 373–376,385–387,753')}.
4. When due, eligible and adequately resourced, securities and cash are posted. As an explicitly labelled economic illustration, the seller’s securities holding decreases by 100, the investor CSD’s omnibus holding at the issuer increases by 100, and the buyer’s holding at the investor CSD increases by 100, with corresponding technical mirror entries maintaining the chain. The linked cash movement decreases the buyer-side eligible cash account by EUR 1,000 and increases the seller-side account by EUR 1,000; cash agents may own those accounts. These are layers of the same 100-share position, not a second issuance. Exact SAC/DCA identifiers and technical posting signs require the actual configured chain and diagrams; they were not certified here. {cite('aa3d5a3b94c9','§1.6.1.8 PDF 303–304; §1.6.1.10 PDF 375,385–387')}.
5. Native message families in the reviewed R2026.JUN overview include inbound sese.023.001.11; outbound sese.024.001.12 status, sese.025.001.11 settlement confirmation and sese.032.001.11 realignment notification. A realignment notification does not itself prove the trade settled; status and confirmation semantics matter. Local participant relays are service-dependent. {cite('aa3d5a3b94c9','PDF 753 and 778')}.

For a Monday trade with Wednesday ISD, assuming three applicable consecutive business days, the Wednesday T2S day can open Tuesday evening, no earlier than 18:45 after the previous day completes. The current baseline gives NTS at 20:00. Eligibility, holidays and operational incidents can change actual execution; a match on Monday is not Wednesday settlement. In Milan the reviewed Art 72 defines SF3 at the relevant cash debit, or securities debit for FoP. {cite('aa3d5a3b94c9','PDF 157,160,163,165,168')}; {cite('8719262f5e8b','Article 72 PDF 51')}.

This single-ISIN DvP example does not establish atomic exchange of two securities. That question needs the proposed two-leg structure, supported linking conditions, both securities’ eligibility and applicable legal finality. The audit found no reviewed production specification supporting such a general claim.
''')

st=stats
write('AUDIT-REPORT.md',f'''# Independent audit — Euronext CSD / T2S knowledge library

**As of 13 September 2026. Verdict: useful evidence library, not ready for unrestricted operational answering.** It can support cited explanations of selected settlement concepts, local participant requirements and regulatory responsibilities. It cannot yet reliably give complete production instructions, current local cut-offs, instrument eligibility, fees/tax answers or full onboarding/default procedures across all five CSDs.

The archive is intact and many source distinctions are already sensible. The main risk is admitting an entire current-labelled document despite unresolved dates, scope, missing diagram content or unreviewed clauses. No deployed retrieval application/index was located. This audit changes no original archive, manifest or generated explanation; every recommendation is a proposal.

## Highest-priority corrections

1. **Resolve the Milan timetable conflict.** Both English and Italian current-linked settlement instructions retain 19:30 NTS / two partial windows; current T2S R2026.JUN gives 20:00 / five. Quarantine those local passages and obtain the applicable notice chain. Add dated ECB exceptions: on 8 September the announced EUR DvP cut-off moved to 17:00. See F01–F02.
2. **Remove the ISIN workbook’s broad current admission.** Its scope is European Offering listing data, with designated/alternative places from 21 September. It is not universal current Milan eligibility. See F03.
3. **Use section-level admission and repair extraction.** The matching-field diagram is missing from text despite a text-rich page; DORA’s English-labelled original has French operative text. Keep roles, service, language, release, dates, footnotes and exceptions with every claim. See F04–F06.
4. **Close specific authority and procedure gaps.** Athens is principally an edition/amendment label issue in the reviewed history, while Oslo’s edition-specific approval reservation remains unresolved. Public Porto layouts should be reviewed before seeking client-only specifications. See F07–F12 and the missing-source queue.

## What was actually checked

| Measure | Audit result |
|---|---:|
| Catalogue URL entries given a provisional metadata decision | {st['catalogue_records_screened']} |
| Retained originals / unique content hashes | 800 / 787 |
| Archived webpage records / selected legal captures screened | 357 / 14 |
| Additional discussion URLs / user attachment records screened | 6 / 1 |
| All decision records, including audit additions and overlapping origins | {st['register_records_including_overlapping_origins']} |
| Sources with substantive sampled review | {st['substantively_reviewed_source_records']} |
| Of these, archived document records | {st['substantively_reviewed_archived_documents']} |
| Live requests / HTTP 200 responses | {st['live_requests']} / {st['live_http_200']} |
| Existing document URLs compared by SHA-256 / unchanged | 62 / 62 |
| Live identity checks on existing current-local/current-infrastructure candidates | {st['live_identity_checks_on_existing_current_operational_layer']} |
| Whole operational manuals certified in every provision | 0 |
| Practical coverage rows / evaluation cases | {len(M)} / {len(E)} |
| Retrieval tests actually run | 0 |

The 33 substantive source records comprise 22 archived documents, three additional local-language PDFs, six legal-text records and two operational web sources. Sampling a long manual is not a full-document review. The 39 operational live checks verify availability/identity and current source trails, **not** all service applicability or supervisory approvals. The 62 unchanged hashes cover a selected subset, not all 800 remote sources. All 800 retained originals matched their archived hashes locally. Metadata-only categories remain provisional and never grant admission. Overlapping inventory origins are not additional independent authorities.

Official live checks covered all five CSDs’ documentation hubs, ECB SDD/releases/status, ESMA, EUR-Lex and national-authority routes. Banca d’Italia, Danish and Norwegian Finanstilsynet and the Portuguese official Gazette were accessible; the HCMC CSD route refused the connection. One guessed Italian rules URL returned 404; the working Italian source route and originals were then used. Full independent national authorisation/approval decisions were not obtained. Browser/web reading recovered selected legal material where direct HTTP was incomplete; no authenticated client service was inspected.

## Deliverables

- [Prioritised findings](FINDINGS.md): 12 findings with source, exact locator, likely answer error and correction.
- [Source decisions, CSV](SOURCE-DECISIONS.csv) and [JSON](SOURCE-DECISIONS.json): one provisional decision for every inventory record, plus additions; no whole-document admission.
- [Reviewed source ledger](REVIEWED-SOURCES.md) and [date/amendment relationships](SOURCE-RELATIONSHIPS.json): precise sampling, approval limits and separate temporal states.
- [Coverage matrix](COVERAGE-MATRIX.md), [CSV](COVERAGE-MATRIX.csv) and [JSON](COVERAGE-MATRIX.json): 83 practical questions with roles, evidence and gaps.
- [Missing/replacement material](MISSING-SOURCES.md): 17 prioritised document dependencies with official routes and access status.
- [Retrieval proposal](RETRIEVAL-PROPOSAL.md) and [machine-readable proposal](RETRIEVAL-PROPOSAL.json): bounded allowlists, exclusions, metadata and extraction/chunking controls.
- [Explanation/claim review](CLAIM-REVIEW.md): assessment of existing summaries and a qualified cross-CSD explanation.
- [Evaluation set](EVALUATION-SET.md) and [JSON](EVALUATION-SET.json): 34 evidence-backed expected answers; **all NOT RUN**.
- [Verification results](VERIFICATION.md): archive preservation, artifact consistency and known static defects.

New downloads, extracts, HTTP timestamps, redirects and hashes are in `sources/`, `extracted/` and `evidence/`. The scripts reproduce the reports from the retained evidence and explicit review annotations; they do not independently perform semantic review.

## Scope limits

This was risk-based sampling, prioritising Milan/T2S and the existing date/authority flags. It did not read 29,084 PDF pages, verify all instrument links, inspect all fee rows, certify all message schemas or assess every legal provision. It did not authenticate to MT-X, CLIMP, MyVPS, MyEuronext or MyStandards. The 14 archive member lists were inspected, but their contents were not fully parsed. Only two original PDF pages and the existing generated cross-CSD image were visually reviewed; other saved PNGs are rendered evidence, not additional visual-review claims. No successful RAG retrieval or answer-quality score is claimed.

The first implementation step is the narrow section allowlist and conflict quarantine, followed by extraction repair and the current Milan notice/interface dependencies. Broader coverage should be earned by closing specific matrix questions and then running the supplied evaluation set.
''')
write('README.md','# Audit outputs — 13 September 2026\n\nStart with [AUDIT-REPORT.md](AUDIT-REPORT.md). Original library files were preserved; this directory contains independent evidence and proposed changes only.\n\nRebuild reports with `python3 scripts/finish_report.py`; run preservation/consistency verification with `python3 scripts/verify_audit.py`. Rebuilding does not fetch live sources. Retrieval evaluations are fixtures marked NOT RUN.\n')
